In [10]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

# Generating dataset

In [3]:
data=make_classification(n_samples=5,n_features=2,n_informative=2,n_redundant=0,n_classes=2)

In [4]:
data

(array([[ 0.52760827, -2.2798078 ],
        [-0.95277662,  1.49696503],
        [ 1.64670695, -1.70914876],
        [ 1.17768946,  0.6035075 ],
        [-0.8855235 , -1.23616948]]),
 array([0, 0, 1, 1, 0]))

# Tuple Unpacking

## Extracting Feature

In [5]:
x=data[0]

In [6]:
y=data[1]

In [7]:
x

array([[ 0.52760827, -2.2798078 ],
       [-0.95277662,  1.49696503],
       [ 1.64670695, -1.70914876],
       [ 1.17768946,  0.6035075 ],
       [-0.8855235 , -1.23616948]])

In [8]:
y

array([0, 0, 1, 1, 0])

# Performing Test Splitng

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)


# performing Min_Max scalling ( range(0,1) for data Normolization)

In [16]:
from sklearn.preprocessing import MinMaxScaler

In [17]:
sc=MinMaxScaler()

In [20]:
sc.fit(x_train)

MinMaxScaler()

In [21]:
x_train_scalled=sc.transform(x_train)

In [22]:
x_train_scalled


array([[0.        , 0.36195775],
       [1.        , 0.19791767],
       [0.55805812, 0.        ],
       [0.81478088, 1.        ]])

# Performing test scalling

In [24]:
x_test_scalled=sc.transform(x_test)

In [25]:
x_test_scalled

array([[-0.02655885,  1.3098716 ]])

# Performing MInMax Scaling ( range = (-1, 1))

In [26]:
sc2=MinMaxScaler(feature_range=(-1,1))

In [29]:
x_train_new=sc2.fit_transform(x_train)

In [30]:
x_train_new

array([[-1.        , -0.2760845 ],
       [ 1.        , -0.60416467],
       [ 0.11611625, -1.        ],
       [ 0.62956176,  1.        ]])

In [32]:
x_train_test=sc2.transform(x_test)

In [33]:
x_train_test

array([[-1.0531177,  1.6197432]])